name: WolkenWelten TS CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --save-dev
      - name: Check types / circular dependencies
        run: npm run check
      - name: Build
        run: npm run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
