name: WolkenWelten - CI

on:
  push:
  pull_request:

# Add concurrency to cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    if: false

    steps:
    - uses: actions/checkout@v4

    # Add Docker layer caching
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and cache Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: app:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  checks:
    name: Checks / Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Check types / circular dependencies
      run: npm run check
      
    - name: Build
      run: npm run build

  deploy:
    name: Deploy to Production
    needs: [checks] # docker is disabled for now
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger deployment webhook
      run: |
        PAYLOAD='{"repository":"${{ github.repository }}","commit":"${{ github.sha }}"}'
        HMAC=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" | cut -d' ' -f2)
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=$HMAC" \
          -d "$PAYLOAD" \
          ${{ secrets.WEBHOOK_URL }}
